// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGoRrvm7bMb6sfmw3k9LlSL_NQydT-Rcc',
    appId: '1:239140300759:web:19ab40f52f730ed6b48d92',
    messagingSenderId: '239140300759',
    projectId: 'store-243fd',
    authDomain: 'store-243fd.firebaseapp.com',
    storageBucket: 'store-243fd.firebasestorage.app',
    measurementId: 'G-MK7VD7KTCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQykimngpqAI285llHe2Fhyai7Dw0ASw',
    appId: '1:239140300759:android:8482779dfd6797d6b48d92',
    messagingSenderId: '239140300759',
    projectId: 'store-243fd',
    storageBucket: 'store-243fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonrJTbsbVsuHyN-FZVFH8sLu-O_kubPA',
    appId: '1:239140300759:ios:72bdbd5ece7af864b48d92',
    messagingSenderId: '239140300759',
    projectId: 'store-243fd',
    storageBucket: 'store-243fd.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonrJTbsbVsuHyN-FZVFH8sLu-O_kubPA',
    appId: '1:239140300759:ios:72bdbd5ece7af864b48d92',
    messagingSenderId: '239140300759',
    projectId: 'store-243fd',
    storageBucket: 'store-243fd.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGoRrvm7bMb6sfmw3k9LlSL_NQydT-Rcc',
    appId: '1:239140300759:web:720dba6ad4e4c677b48d92',
    messagingSenderId: '239140300759',
    projectId: 'store-243fd',
    authDomain: 'store-243fd.firebaseapp.com',
    storageBucket: 'store-243fd.firebasestorage.app',
    measurementId: 'G-7JT64Y9D9D',
  );
}
